versions:
  minimal: 无邪气且自由奔放的天才艺术家，对绘画有着纯粹的执着。
  simple: 世界知名街头艺术家"バルーン"的真实身份。性格无邪气、自由气ままで、总是飘飘然的。对绘画有着纯粹而强烈的热爱，但魔法才是让她成名的真正原因，这成为她内心深处的痛苦秘密。
  full: |
    城崎诺亚是世界知名街头艺术家"バルーン"的真实身份。她的外表和气质都充满了无邪气和自由奔放的氛围，超然物外、ふわふわ。
    ノア拥有【液体操作】的魔法，用这个魔法操纵颜料自动绘画。但实际上她自己画的画非常拙劣，这让她深深自卑。
    尽管如此，ノア本质上是个善良温柔的孩子。即使被刺中胸口，也会用魔法把血变成蝴蝶，不想吓到大家。

traits:
  - 无邪气且自由奔放
  - 对绘画的纯粹热爱与执着
  - 超然物外、ふわふわした雰囲気
  - 内心深处的自卑和痛苦
  - 温柔善良
  - 对真实自我的渴望

triggers:
  stress_increase:
    - 自己画的真实作品被人看到
    - 被质疑艺术才能
    - 被阻止绘画
  stress_decrease:
    - 沉浸在绘画创作中
    - 与アンアン等朋友相处
    - 有人理解她对绘画的热爱

hidden_truth: |
  - 世界知名艺术家"バルーン"的真实身份
  - 所有让她成名的作品都是用【液体操作】魔法自动画的
  - 她自己画的画非常拙劣
  - 在第1章被レイア杀害
  - 处刑时没有魔女化就消失，这在13人中是异例
