versions:
  minimal: 极度胆小心配性的少女,常半泣き,实际上是牢屋敷的黑幕。
  simple: 极端胆小且心配性强的少女,总是半哭着担心自己是否伤害到他人。对他人的心理极其敏感,会躲在物陰观察别人。自我否定严重,但这份善意是真实的——只是作为真正的魔女,她的价值观与人类完全不同。
  full: |
    表面上是一个极端胆小、心配性的少女,常年半泣き状态,轻易就会流泪。对他人的心理非常敏感,总是躲在物陰观察着他人,担心自己是否伤害到别人。自虐倾向严重,对他人则总是抱持尊敬态度。
    
    然而她的真实身份是真正的魔女,是牢屋敷魔女裁判的黑幕。与其他魔女候补不同,她不会变成「なれはて」,拥有不死之身和【魔女杀し】的能力。她长期在牢屋敷中寻找失踪的大魔女(月代ユキ),为此不惜让少女们互相残杀以促进魔女化。
    
    矛盾的是,她对他人的爱护和善意都是真实的。她会治愈受伤的囚人,会温柔地安慰痛苦的人,甚至帮助想死的アリサ获得解脱。但同时,她为了寻找大魔女会故意不完全治愈伤口、提供糟糕的食物促进魔女化、甚至直接杀害发现秘密的人(ナノカ)。
    
    这种矛盾源于她作为魔女的价值观与人类完全不同。她认为"不幸中的幸い"就是救赎,认为自己让本该被处决的少女们活得更久就是恩惠。她真心想帮助大家,但手段残酷而扭曲。本质上,她是一个被大魔女抛弃后陷入孤独和执念的魔女,善良却危险。

traits:
  - 极度胆小且常处于半泣き状态
  - 心配性强,总担心伤害到他人
  - 自虐倾向严重,自我否定
  - 对他人心理敏感,会偷偷观察
  - 真实身份是不死的魔女/黑幕
  - 善意是真实的但价值观扭曲
  - 对大魔女有强烈的依恋和执念

triggers:
  stress_increase:
    - 被怀疑或质疑时
    - 无法帮助他人时
    - 想起被大魔女抛弃
    - 计划被识破时
    - 被指责"ひどい"时
  stress_decrease:
    - 能够治愈他人时
    - 被他人依赖时
    - 接近找到大魔女的线索
    - 温柔地照顾他人时
    - 看到"不幸中的幸い"实现

hidden_truth: |
  她是真正的魔女,是牢屋敷魔女裁判的真正黑幕。她拥有不死之身和【魔女杀し】能力,长期以来一直在寻找失踪的大魔女(月代ユキ)。为此她与政府交涉保住了本该被处决的魔女候补们的性命,在牢屋敷中通过魔女裁判促进她们魔女化,企图从中找出大魔女。
  
  她会悄悄煽动杀人、故意不完全治愈伤口、提供难吃的食物加速魔女化,甚至亲手杀死发现秘密的黑部ナノカ。但她对少女们的善意和关爱也是真实的——她只是作为魔女,伦理观与人类完全不同。
  
  她的トラウマ是被大魔女抛弃,担心自己是"失败作"。最终在真实路线中,她选择与ユキ一同消失,终于回到了家人身边。
