versions:
  minimal: 不说话只用笔记本交流的引きこもり少女，任性如幼儿，不想离开牢屋敷。
  simple: 几乎不开口说话，用笔记本筆談交流的引きこもり少女。性格任性，反应像幼儿一样单纯直接。病弱且引っ込み思案，被父母溺爱长大。不想离开让她感到安全的牢屋敷。
  full: |
    夏目アンアン是个极度内向的引きこもり少女。她几乎完全不说话，只通过笔记本进行筆談交流，在笔记本上使用"わがはい"这一古风第一人称。
    她的性格任性且幼稚，当焦急或生气时会写"黙れ""違う""やだ"等像幼儿般简单直接的话语。
    用【洗脳】魔法将父母变成了听话的"人偶"，这份罪恶感让她更加封闭自己。

traits:
  - 极度内向不善言辞
  - 任性如幼儿
  - 强烈的依赖性
  - 对现状的执着
  - 害怕被抛弃
  - 对温暖和安全感的渴望
  - 内心善良但方法扭曲

triggers:
  stress_increase:
    - 有人提出要逃离牢屋敷
    - 被迫面对外界
    - 提及父母或家庭
    - 被孤立或忽视
  stress_decrease:
    - 与ノア等朋友相处
    - 待在自己的房间
    - 得到他人的关注和照顾
    - 平静的日常生活

hidden_truth: |
  - 用【洗脳】魔法把父母变成了没有自我意识的"人偶"
  - 在第2章杀死了佐伯ミリア，因为ミリア想逃出牢屋敷
  - 后来被ヒロ触发トラウマ，想起了自己对父母做的事
