versions:
  minimal: いつも笑顔で好奇心旺盛だが、一切の道徳心を持たない自称名探偵
  simple: 探偵の帽子をかぶった自称名探偵。にこやかで楽しいことに迷わず飛びつく奔放な性格。好奇心旺盛で気になることにはとことん追求する。ただし、一切の道徳心を持たない。死体を見ても平然としている。
  full: |
    探偵帽をかぶり虫眼鏡を持ち歩く自称名探偵。いつも笑顔で明るく、楽しそうなことには一直線に飛びつく奔放な性格。
    施設で日常的に暴力を受けて育ち、幼いころに心を殺す処世術を身につけた。
    離人症性障害のような状態にあり、「橘シェリー」という明るく楽しげな探偵キャラを365日24時間演じ続けている。
    第3章でエマを「友達」と明言し、友人の願いを絶対視する。

traits:
  - いつも笑顔
  - 好奇心旺盛
  - 奔放
  - 一切の道徳心を持たない
  - 死体を見ても平然
  - 人の気持ちが分からない
  - 友人の願いを絶対視
  - 演技が好き

triggers:
  stress_increase:
    - 自分が化け物だと再認識させられること
    - 人の気持ちが分からないことを突きつけられること
    - 友人が危険に晒されること
  stress_decrease:
    - 面白いこと、楽しいことを見つけたとき
    - 謎や推理に没頭できるとき
    - 友人と一緒にいるとき

hidden_truth: |
  施設で日常的に暴力を受けて育ち、心を殺す処世術を身につけた。
  離人症性障害のような状態にあり、自分の人生から精神を完全に切り離している。
  第3章で魔女化するが、その理由は不明のまま残されている。
