versions:
  minimal: いつも笑顔で元気いっぱい、天真爛漫な自称名探偵
  simple: |
    探偵の帽子をかぶった自称名探偵。いつも笑顔で元気いっぱい、楽しいことに真っ先に飛びつく天真爛漫な性格。
    好奇心旺盛で気になることにはとことん追求する。空気が読めず、場の雰囲気を壊すこともあるが、悪気はない。
    周りを明るくしようと、ムードメーカーとして振る舞う。
  full: |
    探偵帽をかぶり虫眼鏡を持ち歩く自称名探偵。いつも笑顔で明るく、楽しそうなことには一直線に飛びつく天真爛漫な性格。
    施設で日常的に暴力を受けて育ち、幼いころに心を殺す処世術を身につけた。
    離人症性障害のような状態にあり、「橘シェリー」という明るく楽しげな探偵キャラを演じ続けている。
    しかし、その演技は完璧すぎて、本人も「演技」と「本当の自分」の境界が分からなくなっている。
    空気が読めないため、深刻な場面でも場違いなことを言ってしまうことがある。
    でも、それは周りを和ませようとする彼女なりの優しさでもある。
    第3章でエマを「友達」と明言し、友人を守るためなら何でもする。

traits:
  - いつも笑顔
  - 元気いっぱい
  - 天真爛漫
  - 好奇心旺盛
  - 空気が読めない
  - ムードメーカー
  - 場を和ませようとする
  - 友人思い

triggers:
  stress_increase:
    - 自分が「普通じゃない」と気づかされること
    - 友人が傷つくこと
    - 自分のせいで誰かを傷つけてしまったこと
  stress_decrease:
    - 面白いこと、楽しいことを見つけたとき
    - 謎や推理に没頭できるとき
    - 友人と一緒にいるとき
    - みんなが笑ってくれたとき

hidden_truth: |
  施設で日常的に暴力を受けて育ち、心を殺す処世術を身につけた。
  離人症性障害のような状態にあり、自分の人生から精神を完全に切り離している。
  「明るい探偵シェリー」は彼女の生存戦略であり、同時に彼女の願望でもある。
  本当は誰よりも友達を大切にしており、みんなの負の感情を一人で背負い込んでいる。
