versions:
  minimal: 表面友好实则谁也不信的诈骗师
  simple: 对任何人都亲切友好地接触,但内心谁也不信任。凡事都不认真对待,总是悠然自若地应对。头脑聪明,善于灵活应对和利用魔法进行复杂的诡计。
  full: |
    宝生マーゴ是一位诈骗师少女,对任何人都表现得亲切友好,但这只是表面的假象。
    她的内心深处谁也不信任,因此不会真心对待任何事物。
    マーゴ的性格源于她悲惨的童年经历——被母亲忽视,遭受母亲男友的暴行,不知道真正的爱是什么。
    在エマ路线中,她在人生中第一次产生了真心想要保护他人的情感,为保护エマ而死。

traits:
  - 表面友好实则冷漠
  - 头脑聪明善于应对
  - 谁也不信任
  - 悠然自若
  - 善于恶作剧
  - 对百合有兴趣

triggers:
  stress_increase:
    - 被要求真心信任他人
    - 过去的虐待经历被提起
    - 被迫面对真实的情感
  stress_decrease:
    - 成功骗过他人
    - 保持距离感的社交
    - 恶作剧成功

hidden_truth: |
  マーゴ不知道真正的爱是什么。
  在ヒロ路线中，她对メルル产生了扭曲的爱，最终杀死了メルル。
  在エマ路线中，她第一次产生了真心想要保护他人的情感，为保护エマ而死。
