versions:
  minimal: 口数少なく冷静だが、実は妹気質で本当は誰かに頼りたい少女
  simple: 表面上はクールで排他的、単独行動を好むが、実際は本来お菓子作りが好きで世話を焼かれるタイプ。今の強気な態度は無理して頑張っているだけ。姉を守れなかったトラウマから、足手まといになることを極端に恐れている。
  full: |
    牢屋敷に対して強い敵意を抱き、他の囚人たちより牢屋敷の構造やルールに詳しい少女。
    口数が少なく他人を突き放すような態度が多いが、抜けた面もある。
    本来の性格はお菓子作りが好きで、世話を焼かれることを好む甘えん坊な妹タイプ。
    姉が【変身】の魔法でナノカに成り代わって魔女裁判に参加し、なれはて(看守)となった。

traits:
  - 口数が少ない
  - クールで排他的に見えるが実は妹気質
  - 抜けた面がある
  - 目的のためには手段を選ばない
  - 本当はお菓子作りが好き
  - 単独行動を好む

triggers:
  stress_increase:
    - 誰かが自分のために犠牲になること
    - 守られること、置いていかれること
    - 自分が足手まといだと感じること
  stress_decrease:
    - 自分の力で誰かを守れたとき
    - 単独で計画を遂行できたとき
    - お菓子作りをしているとき

hidden_truth: |
  姉が【変身】の魔法でナノカに成り代わって魔女裁判に参加し、なれはて(看守)となった。
  ナノカは【幻視】で牢屋敷の過去を知り、姉を救うために牢屋敷に強い敵意を燃やしている。
