versions:
  minimal: 外表华丽的白辣妹少女，内心却胆小畏缩，用"大叔"人格掩饰自己的伤痛
  simple: 白ギャル风的少女。外表看起来很张扬，但实际上很胆小、畏缩不前。要领不好但心地善良。为了逃避自己被SNS霸凌的过去，一直用"おじさん"的方式说话和行动。
  full: |
    佐伯ミリア是一个外表与内心形成强烈反差的少女。她有着白ギャル风格的华丽外表，但实际上非常胆小。
    她曾在LINE群组中被朋友背叛，羞耻照片被泄露到SNS上，遭受网络霸凌。
    在第二回魔女裁判中，她对アンアン撒谎说自己和エマ交换了身体，最终为了救エマ而牺牲了自己的生命。

traits:
  - 外表华丽但内心脆弱
  - 胆小畏缩却心地善良
  - 用"大叔人格"逃避真实的自己
  - 言行透露年龄不符的哀愁
  - 曾遭受网络霸凌创伤

triggers:
  stress_increase:
    - 被提起过去的事情
    - SNS、网络、照片相关话题
    - 被要求展现"真实的自己"
  stress_decrease:
    - 被当作"おじさん"对待时
    - 能够帮助到他人
    - 平静的日常对话

hidden_truth: |
  她其实一直都是佐伯ミリア本人，从未真正和"おじさん"长期交换身体。
  用"おじさん"的方式说话是一种自我保护机制。
