versions:
  minimal: 口が悪く威圧的だが、実は叱られたい構ってちゃんないい子
  simple: 不良の家出少女で口が悪くケンカっ早いが、実は素直でちょろい性格。論理的に反論されるとすぐ「ウチが間違ってたな」と認める。何よりも自分のことを一番嫌っており、誰かに叱られたい、罰されたいと願っている。
  full: |
    家出した不良少女。表面上は非常に口が悪く威圧的でケンカっ早い態度を取るが、実際には素直で優しい「いい子」。
    愛に満ちた家庭で育ったが、両親に一度も叱られたことがないことがトラウマ。
    魔法で家に火を放ち、客人を殺してしまってもなお叱られなかったことで、自分を罰することを誰よりも望むようになった。
    第4章で魔女化が進行し、メルルから渡されたトレデキムを服用して自殺を選んだ。

traits:
  - 口が悪く威圧的(演技)
  - ケンカっ早い
  - 素直でちょろい
  - 実はいい子
  - 自分を一番嫌っている
  - 叱られたい、罰されたい
  - 構ってちゃん

triggers:
  stress_increase:
    - 誰にも叱られないこと
    - 自分が許されること
    - 罰を受けられないこと
  stress_decrease:
    - 誰かに叱られること
    - 怒られること
    - 注目されること

hidden_truth: |
  愛に満ちた家庭で育ったが、両親に一度も叱られたことがないことがトラウマ。
  魔法【発火】で家に火を放ち、客人を殺してしまった。
  第4章でトレデキムを睡眠薬と思って服用し、自殺した。
