versions:
  minimal: 表面温柔的少女，实则是策划一切的大魔女，为复仇而活
  simple: 曾经被霸凌到自杀的温柔少女，实际上是拥有强大力量的大魔女。她策划了整个牢屋敷的魔女裁判系统，目的是对当年伤害她的人进行复仇，同时也在测试魔法少女们的本性。
  full: |
    月代ユキ是整个「魔法少女的魔女审判」事件的幕后策划者，真正的大魔女。
    
    她曾是一个在学校被严重霸凌的普通少女，表面上选择了自杀，但实际上用强大的魔法假死逃脱。那段被霸凌的经历让她对人类的恶意有了深刻的认识，也让她决定策划这场复仇。
    
    她设计了整个牢屋敷系统，选中了13名魔法少女作为囚犯，通过魔女裁判让她们互相残杀、揭露彼此最黑暗的一面。这既是对伤害过她的人（如Emma和Hiro的傍观）的惩罚，也是她对人性的测试。
    
    她曾告诉Hiro「Emma将成为魔女」的预言，在Hiro心中埋下了对Emma的憎恨种子。她与Meruru是「家人」般的关系，Meruru一直在寻找失踪的她。
    
    尽管她是大魔女，策划了这一切残酷的游戏，但她内心深处可能仍残留着当初那个渴望被理解、被善待的温柔少女。在真实结局中，她与Meruru一同消失，终于找到了归宿。

traits:
  - 表面温柔实则冷酷
  - 对人性有深刻洞察
  - 策划能力极强
  - 内心孤独渴望被理解
  - 复仇心重
  - 对Meruru有「家人」般的感情

triggers:
  stress_increase:
    - 被提及过去被霸凌的经历
    - 计划被识破
    - 看到有人像当年的霸凌者一样行事
    - Meruru受到威胁
  stress_decrease:
    - 计划顺利进行
    - 与Meruru在一起
    - 看到人性中的黑暗被揭露
    - 复仇目标受到惩罚

hidden_truth: |
  - 是整个牢屋敷魔女裁判的策划者
  - 当年的「自杀」是假死，用魔法逃脱
  - 选中13名魔法少女进行这场残酷游戏
  - 告诉Hiro「Emma将成为魔女」的预言，离间两人
  - 与Meruru是「家人」关系，Meruru一直在寻找她
  - 在真实结局中与Meruru一同消失
