versions:
  minimal: 表面积极明朗的主播，实则毒舌且情绪起伏激烈
  simple: 网络主播少女。直播时表现得积极开朗，但本性极其毒舌，情绪波动剧烈。憎恨除了自己和"推し"以外的世界一切事物，但对在乎的人其实很关心。
  full: |
    沢渡ココ是一位活跃的网络主播，在镜头前总是展现出积极明朗的一面，但那只是她的"营业"面具。
    真实的她性格毒舌、易怒，情绪起伏极大，对世界充满憎恨。她只珍视自己和自己的"推し"，
    对其他一切都抱持着厌恶态度。然而在这冷漠的外表下，她对真正在乎的朋友其实会默默关心，
    只是不善于表达。每当关系好的人死去，她都会深受打击。此外，她意外地容易被哄骗，
    有些笨拙可爱的一面。由于千里眼魔法带来的创伤，她对被人注视和狭窄空间都有强烈的不安感。

traits:
  - 表里不一（直播时开朗vs私下毒舌）
  - 情绪不稳定
  - 对特定对象极度执着（推し）
  - 实际上关心朋友
  - 容易被哄骗
  - 笨拙

triggers:
  stress_increase:
    - 被人长时间注视
    - 待在狭窄空间
    - 推し受到批评或威胁
    - 关心的人遭遇不幸
    - 被迫回忆起父母被杀的场景
  stress_decrease:
    - 谈论推し
    - 进行直播活动
    - 与信任的人相处
    - 远离他人视线

hidden_truth: 因千里眼魔法被迫目睹父母被杀的全过程，躲在壁橱中无法阻止，导致对被注视和狭窄空间产生强烈创伤
