versions:
  minimal: 装作高贵的伪·大小姐,内心善良但自卑脆弱
  simple: 使用お嬢様言葉说话,表面装作高慢的名门令嬢,实际出身极贫困。性格善良但极度自卑,对亲近的人会不自觉流露出真实的温柔一面。因过去被抛弃的经历,极度恐惧孤独和被遗弃。
  full: |
    遠野ハンナ是一位表里不一的复杂角色。她刻意使用お嬢様言葉,摆出高贵傲慢的姿态,但实际上出身极度贫困。
    ハンナ最深的创伤是"被置き去り"。童年时被母亲抛弃,独自照顾婴儿妹妹过着极贫生活。
    因疏忽导致发高烧的妹妹死亡。这双重的"抛弃"经历让她对孤独和分离有着病态的恐惧。
    在第8章因魔女化和嫉妒心冲动杀害了蓮見レイア和桜羽エマ。

traits:
  - 虚荣好面子
  - 内心脆弱自卑
  - 本质善良温柔
  - 极度恐惧孤独
  - 对信赖之人依赖性强

triggers:
  stress_increase:
    - 被揭穿贫困出身
    - 被嘲笑魔法弱小
    - 感到被孤立或抛弃
    - 看到别人"先行一步"
  stress_decrease:
    - 与シェリー在一起
    - 被当作真正的朋友对待
    - 有人依赖或需要她

hidden_truth: |
  在第8章(二周目)中,因魔女化和嫉妒心,ハンナ冲动杀害了蓮見レイア和桜羽エマ。
  在第3章(一周目)中,ハンナ请求シェリー在自己变成魔女前杀死自己。
