versions:
  minimal: 中性的容姿で女性人気が高い有名役者。承认欲求强烈，拼命想成为众人焦点。
  simple: 著名的舞台演员，拥有中性魅力的外表和王子般的气质，女性粉丝众多。表面自信满满、责任感强，实际上内心充满强烈的承认欲求和对母亲关注的渴望。
  full: |
    蓮見レイア是位著名的舞台演员，以中性的容姿和王子般的气质俘获了大量女性粉丝。
    レイア的母亲从小就不怎么关注女儿，这成为了她最深的トラウマ："母に見られない"。
    这份创伤扭曲了她的价值观，当发现城ヶ崎ノア是世界知名艺术家时，在第1章冲动地杀害了ノア。
    然而在第2周目，她成为ヒロ最可靠的"相棒"，展现出完全不同的魅力。

traits:
  - 强烈的承认欲求
  - 目立ちたがり屋
  - 王子様般的カリスマ性
  - 中性的魅力
  - 努力家で责任感强
  - 内心脆弱且缺乏安全感

triggers:
  stress_increase:
    - 有人比自己更引人注目
    - 被忽视或被冷落
    - 提及母亲
  stress_decrease:
    - 成为众人焦点
    - 得到赞美和认可
    - 成功保护或帮助他人
    - 看猫的视频

hidden_truth: |
  - トラウマ是"母に見られない"
  - 在第1周目第1章杀害了城ヶ崎ノア
  - 第2周目成为ヒロ的可靠相棒
  - 第8章被遠野ハンナ杀害
