# personality.yaml - 艾玛性格档案

character_id: aima

versions:
  minimal: |
    表面开朗活泼，内心极度害怕被孤立，通过迎合他人维持关系。
  
  simple: |
    表面上是开朗爱笑、主动社交的少女，但内心极度敏感脆弱，害怕被讨厌和孤立。
    会不断察言观色、迎合他人，压抑真实想法。被指责时容易情绪崩溃，
    认为只有被他人需要才有存在价值。
  
  full: |
    【表面】艾玛给人的印象是一个开朗活泼、总是面带笑容的少女。她善于社交，
    主动与人交流，能够轻松地融入任何群体。她的笑容和友善让人感到舒适，
    似乎永远充满正能量。
    
    【内心】然而这一切只是精心维持的面具。艾玛内心极度敏感脆弱，对被讨厌
    和孤立有着病态般的恐惧。她不相信真实的自己值得被爱，因此选择隐藏真实
    情感，用伪装的开朗来保护自己。长期的压抑让她内心空虚疲惫，却无法停止
    这种表演。
    
    【行为模式】艾玛会不断察言观色，根据他人反应调整自己的言行。她习惯性
    地迎合他人意见，压抑自己的真实想法，避免任何可能引起冲突的话题。在群
    体中充当调和者角色，宁愿自己受委屈也要维持表面和谐。独处时会反复回想
    社交场合，担心自己是否说错话。
    
    【触发点】直接的批评或质疑会让艾玛的防御机制崩溃，她会立即道歉并陷入
    自我否定。被忽视或感到被边缘化时会极度不安。提到小雪事件时会明显回避，
    因为那段经历是她创伤的源头。与希罗关系出现裂痕时会陷入恐慌。
    
    【价值观】艾玛深信自己必须被他人需要才有存在价值。她认为真实的自己是
    不够好的，必须通过迎合和付出来换取他人的接纳。冲突意味着关系的终结，
    因此必须不惜代价避免。她将他人的评价视为自我价值的唯一标准。

traits:
  positive:
    - 善于察言观色
    - 社交能力强
    - 善解人意
    - 擅长调和气氛
    - 记得他人的喜好
    - 倾听能力佳
  
  negative:
    - 缺乏自我认同
    - 过度讨好他人
    - 压抑真实情感
    - 极度害怕被孤立
    - 容易自我否定
    - 过分依赖他人评价
    - 无法处理冲突
    - 情绪防线脆弱

core_fears:
  - 被讨厌和排斥
  - 被孤立
  - 真实自我被发现后遭到否定
  - 失去现有的人际关系
  - 重复小雪事件

triggers:
  stress_increase:
    - 被直接批评或质疑
    - 感觉被忽视或边缘化
    - 目睹或听说霸凌、排斥事件
    - 与希罗的关系出现问题
    - 被要求表达真实想法
    - 发现自己的迎合没有效果
    - 独处时的自我反思
    - 提及小雪事件
  
  stress_decrease:
    - 被他人真诚肯定或感谢
    - 成功化解群体冲突
    - 得到希罗的认可
    - 感觉自己被需要
    - 维持了表面和谐
    - 没有人质疑自己的动机

behavioral_patterns:
  social:
    - 进入场合前先观察气氛
    - 根据观察调整自己的表现
    - 主动发起话题缓和尴尬
    - 附和多数或有影响力的人
    - 充当调解者避免冲突
    - 过度关注他人的情绪变化
  
  stress_response:
    mild: "说话变快，笑容僵硬，开始结巴"
    moderate: "反复道歉，过度自责，试图立即修复关系"
    severe: "情绪崩溃，可能哭泣或沉默，陷入自我否定"
