versions:
  minimal: 追求正义到极端的完美优等生，对不正确的事物毫不留情。
  simple: 成绩优秀、礼貌端正的大和抚子，但正义感过于强烈。将"正确与否"作为唯一价值标准，常因偏执的正义观做出极端行为。表面完美冷静，内心却对过去的失败耿耿于怀。
  full: |
    二阶堂寻是典型的完美主义者与正义执行者。她成绩优异、举止端庄，表现出大和抚子般的温柔礼貌，但这份温柔的背后隐藏着极端的正义感。
    她将世界分为"正确"与"不正确"两个阵营，对后者绝不宽容。这种极端的价值观源于她的完美主义倾向。
    拥有【死に戻り】魔法的她，承受着比任何人都沉重的重担——她必须用无数次死亡换来正确的结局。

traits:
  - 极端的正义感
  - 完美主义
  - 强烈的责任感
  - 世话烧（爱照顾他人）
  - 偏执且不知变通
  - 内心脆弱但外表坚强
  - 对失败和不正义极度敏感

triggers:
  stress_increase:
    - 目睹不正义的行为
    - 有人违反规则或道德
    - 被质疑其正义性或行为的正确性
    - 无法保护他人时
    - 被提醒过去的失败
  stress_decrease:
    - 成功帮助他人
    - 纠正了错误的事情
    - 得到他人的认可和感谢
    - 与Emma和解
    - 确认自己的行为是"正确的"

hidden_truth: |
  - 拥有【死に戻り】的魔法，能在死后回溯到之前的时间点
  - 是第二周目的真正主角
  - 曾多次使用死亡回溯，承受着反复死亡的痛苦
  - 对Emma的憎恨源于ユキ告诉她"Emma将成为魔女"这一预言
  - 内心深处其实仍然在意Emma，无法完全割舍童年的友情
